apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-rwx-pvc-powerscale
  labels:
    name: busybox-rwx-pvc-powerscale
    csi: powerscale
spec:
  storageClassName: powerscale
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
