apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq
spec:
  selector:
    matchLabels:
      name: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: public.ecr.aws/h1c1m2y2/rabbitmq
          env:
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-mq-password
                  key: password
          ports:
            - name: userport
              containerPort: 5672
            - name: adminport
              containerPort: 15672
