# Please change the name, region, vpc, subnet, instance type and other specs
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ekstest
  region: ap-southeast-1
vpc:
  id: "vpc-00bd9eaaf39bd4daa"  # (optional, must match VPC ID used for each subnet below)
  cidr: "172.24.164.0/22"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      subnet165:
        id: "subnet-0598aeb1e685a1927"
        cidr: "172.24.165.0/24" # (optional, must match CIDR used by the given subnet)

      subnet166:
        id: "subnet-00f8cb3f2675a0a92"
        cidr: "172.24.166.0/24"  # (optional, must match CIDR used by the given subnet)
nodeGroups:
  - name: ng-1
    minSize: 1
    maxSize: 1
    securityGroups:
      attachIDs: ["sg-041a3e0a16b148731"]
    maxPodsPerNode: 80
    instancesDistribution:
      maxPrice: 0.09
      instanceTypes: ["t2.xlarge"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 1
    volumeSize: 16
    ssh:
      publicKeyPath: ~/eks.pub
