# Please change the name, region, vpc, subnet, instance type and other specs
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ekstest
  region: us-east-2
vpc:
  id: "vpc-79741910"  # (optional, must match VPC ID used for each subnet below)
  cidr: "172.31.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      us-east-2a:
        id: "subnet-2615664f"
        cidr: "172.31.0.0/20" # (optional, must match CIDR used by the given subnet)

      us-east-2b:
        id: "subnet-66942d1d"
        cidr: "172.31.16.0/20"  # (optional, must match CIDR used by the given subnet)

      us-east-2c:
        id: "subnet-28549a65"
        cidr: "172.31.32.0/20"   # (optional, must match CIDR used by the given subnet)
nodeGroups:
  - name: ng-1-workers
    minSize: 2
    maxSize: 2
    maxPrice: 0.017
    instanceTypes: ["t3.medium"]   # (insert comma separated values for more instance types) 
    onDemandBaseCapacity: 0
    onDemandPercentageAboveBaseCapacity: 100
    spotInstancePools: 1
    volumeSize: 16
    ssh:
      publicKeyPath: ~/eks.pub
