apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-snapshotter.yaml
  - ./my-powerstore-secret.yaml  
  - ./csi-powerstore.yaml
  - ./powerstore-ext4-iscsi-topology-storage-class.yaml
  - ./powerstore-ext4-iscsi-snap-class.yaml
  - ./metallb-native.yaml
  - ./nginx-ingress-controller.yaml
