apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cluster-1-autoscaler-management
    patch : |-
      - op: add
        path: "/spec/template/spec/nodeSelector"
        value:
          group: md-2
