apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: session-db
  namespace: sock-shop
spec:
  authSecret:
    name: sockshop-db-creds
    externallyManaged: true
  version: 6.2.5
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: 
    accessModes:
    - ReadWriteOnce
  terminationPolicy: Halt
  podTemplate:
    spec:
      nodeSelector:
        group: md-0
