apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patches:
  - path: ./patch-deployment.yaml
    target:
      kind: Deployment
  - path: ./patch-daemonset.yaml
    target:
      kind: DaemonSet
